
# Dependencies
markdown:         kramdown

# Permalinks
#permalink:        pretty

# Setup
title:            'Concepts of Biology'
tagline:          'from http://cnx.org/contents/b3c1e1d2-839c-42b0-a314-e119a8aafbdd@12.1 (CC-BY)'
url:              https://github.com/philschatz/biology-concepts-book
origin:           http://cnx.org/contents/b3c1e1d2-839c-42b0-a314-e119a8aafbdd@12.1

author:
  name:           'Openstax'
  url:            https://github.com/openstax

paginate:         5

# Custom vars
version:          12.1

bookviewer:       https://philschatz.com/book-viewer

